version: '3.8'
services:
  web:
    build: .
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - FLASK_ENV=production

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot
             --webroot-path=/var/www/certbot
             --email your-email@example.com
             --agree-tos
             --no-eff-email
             -d yourdomain.com
             && cp -L /etc/letsencrypt/live/yourdomain.com/fullchain.pem
                    /etc/letsencrypt/live/yourdomain.com/privkey.pem
                    /etc/letsencrypt/live/yourdomain.com/
             && nginx -s reload"
